/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.modules.amazon.fws.config;

import org.mule.tck.FunctionalTestCase;

public class AmazonFwsNamespaceHandlerTestCase extends FunctionalTestCase
{
    @Override
    protected String getConfigResources()
    {
        return"amazonfws-namespace-config.xml";
    }

/*
    public void testSendMessageToFlow()throws Exception
    {
    */
/*
        This test case tests your Mule integration.

        To test your flow directly (i.e. without any inbound endpoints, declare a flow in
        amazonfws-namespace-config.xml and put the element from your
        cloud connector's namespace that you want to test into it.
        A proper example was put into amazonfws-namespace-config.xml

        Now you can send data to your test flow from the unit test:

        String payload = <your input to the flow here>;
        SimpleFlowConstruct flow = lookupFlowConstruct("theFlow");
        MuleEvent event = getTestEvent(payload);
        MuleEvent responseEvent = flow.process(event);
        assertEquals(<expected test output>, responseEvent.getMessage().getPayloadAsString());
    *//*

        //TODO: Get this working, how do I generate my amazonfws schema file for use with MuleConfig.xml? (this is currently causing test to experience exception)
        String payload = "somePayload";
        SimpleFlowConstruct flow = lookupFlowConstruct("testGetServiceStatus");
        MuleEvent event = getTestEvent(payload);
        MuleEvent responseEvent = flow.process(event);
        assertEquals("", responseEvent.getMessage().getPayloadAsString());

    }

    private SimpleFlowConstruct lookupFlowConstruct(String name)
    {
        return(SimpleFlowConstruct)muleContext.getRegistry().lookupFlowConstruct(name);
    }
*/
}
